/* Les contours de la carte, dessinés à partir de points embarqués.

   Fabriqué par `outils/contours.mjs`, à relancer seulement si les contours
   changent. Deux sources publiques : les départements d'après ADMIN EXPRESS de
   l'IGN sous licence ouverte, les côtes et frontières d'Europe d'après Natural
   Earth, domaine public. Les deux sont citées dans les réglages.

   Le fond est dessiné parce qu'un fond en tuiles coûte trop cher. Mesuré le
   5 septembre 2026 sur la Géoplateforme : une tuile de plan pèse de 42 à
   70 kilooctets, et une vue de téléphone en demande une douzaine, soit de six
   cents kilooctets à un mégaoctet par écran, à chaque déplacement. Toute la
   prévision horaire de l'application en pèse cinq.

   Ce fichier pèse 30924 octets de données, une fois pour toutes, et se sert
   avec la coque hors ligne.

   Les coordonnées sont des entiers au pas de 0.002 degré, encodés en différences
   successives sur des entiers de longueur variable, puis en base 64. Le pas vaut
   cent cinquante mètres en longitude à cette latitude, soit un pixel et demi au
   zoom le plus fort que la carte accepte.

   Les limites des départements forment une topologie. Deux départements voisins
   partagent leurs arcs communs, stockés une seule fois, et chaque département
   garde la suite d'arcs qui referme chacun de ses anneaux. Le tracé et le
   remplissage lisent donc les mêmes points : la teinte d'un département épouse
   exactement son trait.

   Ce qui doublait la France a été retiré de l'Europe : les deux sources ne
   s'accordent pas au mètre près, et sans cette coupe la côte et les frontières
   se dessineraient deux fois, à deux kilomètres l'une de l'autre. */

// Le pas de la grille, en degrés.
export const PAS = 0.002;

/* Les arcs des limites de départements, 818 arcs, 6918 points. 151 ne
   sont portés que par un département : ce sont la côte et la frontière. */
const ARCS =
  "5AwErCXg6AIOKhC6JYrpAo4BqAJEBTQbdB4eBw4pKBEEiCn06gI2BwS+Ke7qAgoRMMgp3uoCFxNOIQMdNA8MFxwICgsVKRIJ"
  + "RAQYGCAEFCAgCiIfHgMMMZgBCh4OChoYACo0UDYEsC/Q6gIiCRjSL8jqAkgpMTcDFRMJFiMXDw8INwk5Fw8VHAsE6C7q6AIl"
  + "NxDELrToAkEPCSMdAhkUGz8ENxgTBMotlOcCAyMEyC3y5gIFHRLELdbmAitlA0MdJTUCBBsVEQIVHwsEnCzG5AIlGQT4K67k"
  + "AhcmGuIr1OQCMxwYDDMYaVwMGBUUPyAzJSU7LRcfBCEeBKgo6uUCOwwE7if25QI7AyS0J/TlAn8FAyYPDggOGwYFEiEOKxEA"
  + "GiMSIwMJDBgWD0gWGA8YNkAEwiXM6AIXFATQH/6BAwkJSsgf9oEDBScZAxMUIQAlHh0PIwwbCxIPCRNHCYcBLRpJCSEkAwYZ"
  + "FgkaBAUVLw8TCj8DCyMcJTUXABs8CB4bKQ8TJR0HCg8dBwATLwsVFwS0G/r9AhcnBJ4b1P0CGw0ahBvI/QIJEEkSDzAlDxso"
  + "JQsRIlUsDiwdGAwQPwgEoBjU/wIhCgSAGN7/AhQKSJQY6P8CAg4uChMKBxx1GAIbIwQCFg0MLAoWFRAMDyAKHDcKExgmEigH"
  + "IA4CGBAECEA+AAMMNRAOGhsYGgIKGAceDgIvLhIKDxgSCASsGICEAwIqBK4YqoQDGTQYlhjehAMhGBgKCR4XCh4MAxYkEgMe"
  + "IhwYLA8KBNoYzIYDChAE5BjchgMeBiaCGeKGAxwOMhE6Ag4SigETNCQaAC4dZixkHxQIRB9WGAspIhEqACARNAgErCC6hgMg"
  + "AAbMILqGAxoLAw0E5CCkhgMmAiqKIaaGAxEtJgsJMSMzDA0TDSYdPzk5FQUdHRU3AAsRLCsTFRQbJxMCKRARFQ8Exh+eggMK"
  + "IQTYF8rtAhIlJuoXpu0CUB8iIyIPSCQeAA4dIAUqHi4DAxMWCwIhRCIWCQ4MCxowCBcaBPgbnu0CNgAErhye7QIIKzC2HPTs"
  + "AjoxEi8SCwwnDREKCxoAIhUgDB4XAxMcCxwOKAcoGQsfCAkTHQ4fBzMlAAMRIwkEyh7Y6QIPFQS8HsTpAhcAHKYexOkCCQ1D"
  + "CwMRIwAoTRMJDC0UFxErEjtTFyMIDxkE7hz+5gIAFQTuHOrmAhMcOtwchucCIwYpNHkDHTIjClkVdxRXAycqSw0XFhcDHy4f"
  + "CgIgFgwCFC8MNwMVFQklTxwNDQoRDxEnCRcvEQkE0BSm6AJLGgSGFMDoAgceHIAU3ugCIQwNMhkMDSIlDBcLAxodFBcTLxIX"
  + "GBYMKRQE7BGy6gIDIgTqEdTqAgQiJO4R9uoCUkByDhILHAgIC0oeCSgZDhIiGRY0BVpYGAAUG0YSUDQ0EASQF9TtAkgLBKws"
  + "oNkCEAdWvCya2QJoHHIZBA4hBhckIxADEBgWHg0CESIZDDwfCioqECR2OAgYTA8AFRIDNjsiHhsyOhIeERgiEQwaDDY1FgIk"
  + "FaIBBwwqGAwMKjoKHCJYHAQOFgIiHiIHBKQ27twCDh0QsjbS3AIfIwAVTyscNTgpLxMELwTwNdbaAgkNNug1ytoCTR8bLRkJ"
  + "AxMlDQcpISkWLzAvCyVcNQwjQB0cITsHNxwbCRcbIw0zAgATFQcLFSQJAg9BDQTyM5TWAgcJBOwzjNYCERI23DOe1gI/FyMW"
  + "Kw9FAAAhHxs7DEEkCRIrAx8lKxklABsfKw8EERMLIxwDEjEQABQjAgMVNQ0XHC8IBJYt7NUCGRsE/izS1QIJCiD2LNzVAiEQ"
  + "BRgfCB8mUQQfDQYiGAwgNDEaLwQGLBokACwrBwT+KqDYAgU0BPoq1NgCKhAYpCvk2AIMEh4IEwwMEiIAHhUJES4HBBIlAgYY"
  + "BJQsntkCGAIE9DDG4AIoExycMbTgAiAKHg8MFQsPWBMiBAciHhIUCxoGFBQoAw4NBOYztuACAwko5DOu4AIiHwozSAcIEw8H"
  + "GhUPQ3I5MgUUEEgXDB0TFyxJFgUMIzcMJwUdEwSuNv7cAgsRBKwsoNkCBig+sizI2QILCAQkHQURDAYQHwgKGFECERAdDSMe"
  + "GwIKFhsgHggcDRYSIwoHEhYafBsaJCIAQyouQgMqVA0cFiQJJi4ExC2c3QIbBgSqLaLdAhoiLsQtxN0CEgxMAjocHxZQIhoX"
  + "SC56CxQSHgQkGxIIBFYfBgAWDwoIFEcFMRAQNhgEDyYE1jC04AIeEgToNcraAiINaIo2vtoCBBEiGQUNJhMOLR4NIAhIHxIE"
  + "OicUBiohPAQSHUQABAoeAy4SbAYgHCYFESkwNRErJQsGIRMZORMZEw0pMRERFSJLNycRCjEbAgs3Az8lNwQnLQ0MJQUTExNN"
  + "FQovF1MDJR8QDQcVBKQ23NMCDwUaljbY0wIzFgwaEQgcJAAcbxwnJg4cFSwjACcUGQsEgjTk1QIXKASEI7ThAjgDDrwjsuEC"
  + "PhINFggQGAIJEnA0BPYksuICHgQElCW24gIQDQakJariAgsPCBkEoiWE4gIeEwTAJfLhAgoJOsol6uECB2EKHxAJGyMYFQQh"
  + "HA8VFQMhMEcdHwIhEx8VBRstJRcCNRQnCScjKwIPIQcTGxAbEQ8GQR8XFTsEqCTU2gICKwSqJKraAgQdBK4kjtoCBSEEqiTu"
  + "2QINDDSeJPrZAhUFPxo1JC8CCy8RCyMCCRAOHhMMMwcxGwIVIR9JJAkSJQURGEsVEQwSCgMmEBwVDAscBMYfntsCKQ4Enh+s"
  + "2wILDA6UH7jbAgcsIzgZAB8uACIZGgSeHobdAglCBJYeyN0CHAgysh7Q3QIwLAYcLAsoFAkMDhp6Ajw8BhxaChcaCBQQDEIG"
  + "AxIhEBoiHAwfDgYORg0CHhgSEiwEiiOo4QIHDASKIaaGA0oMUtQhsoYDKhNgD0AIQCJkEBo6Ew4UHDIQChg+GDgJDhMZCwMb"
  + "EQQXNwoLM0UADTwNKCUnMRAXDTFKBxoQKgMKEzgVGgQkNSgHABFOBxgKQCsZEwQXHgwE3inagwM0CSqSKtKDAw8ZKQMdITMT"
  + "HxxHBxMaGwQdNQoHJyUWERY7ExUQEQ8VHwIjJRgzVycE5CbggAMPDQTWJtSAAykcHq4m8IADVR0LDkkJOw4zGT1AdRMrCCse"
  + "Rww7Ni8CDw5xBATsH/qBAx0EBJgNitICDA86pA380QIAERgVCyduKTgFEBsWEiAPBiMPIywVAEMzDQMPLgsMGQcjKRFHBQcl"
  + "HAkUGwUZJhc4AzIWGgVcRwSAEbrNAgsTBPYQqM0CJwgM0BCwzQKFAQ0ZK0ELIxtZCQT6Dc7MAg0GLu4N1MwCMQoMFoUBEDkc"
  + "RwULGQgPJwsbMhsQAhAlDgQQawAZDEMRHRIHGhcQexAZEiURBJwHps4CQyRU2gbKzgIhWDwWDRZqECQkHxIAIhQSEQwcEBQJ"
  + "FihIDEwjECEmBgMSIA4TFD0SHhxMAD4mSyQRGBoIBg4aBj4vDg8JHR4ROAoAHA8IBiIWAwAVHgZaFSQaBIoNktICDgkE1hqG"
  + "+gIIGBTeGp76Ah8KDhwTHC4SHR42AhQODxomIgSwG9z7AjQQBOQb7PsCGBE8/Bvc+wIYIRwDDCNiA1ATLBYJFg4UHAcQIiIF"
  + "NDw4AhYkNBEeFIwBBhgNBh8PEw4XEw9aN1wZGggGEzAWMgQKCwScJKD7AiINBL4klPsCFT8oqiTW+gIPDyQNHDE8CQcXWBsd"
  + "ESQdCQ0QEQ8bEisZIQwbFQ0GF2sKKy0YGQToJLL3AgkfBOAklPcCHwUQwiSQ9wJdDi8dGB9xDyMKPw0rBgTWIdr2AhElBMYh"
  + "tvYCHQNQqiG09gItGgYUFwICGysONyMzFBEVHQIPDhMNVQgMJg8WFxMdBAsUHgwvGhU8HxwjAg4SDxQjGycFGywXBhsNEwou"
  + "JhcMGBAJEh0IABRbRC8GGQ8E5Bro+QIPHgSYDYrSAhQSGqwNnNICBQoWDAMQIBIQDSAWACI2NC4nNBQgExoGBN4PltMCEBYE"
  + "7g+s0wIYBxqGEKbTAhAZKA0+FhAXHAsOGgkSKhqEASUmEj4AGA0E2BOg0wIuAwSGFJ7TAhwLMKIUlNMCKR8HLSQFEiU4BSQa"
  + "Bic0HRQEFCRMJAQsEgkFJTwTOggCJTAFOBsMCBoPNgImJwSoGczRAj8vCuoYntECaYEBIU8DHxQNBPQXps8CEVEe5BfWzgJ/"
  + "LjUiTRczOz0JswEWMxFHDDcLHm09HysDCxFHHwSAEZzNAgsMBKARyNwCABw4oBHk3AJ2GgYVIgkQCDYNMAwQKDoiCDYiDgUc"
  + "EAoLDoIBXCoVAz0eEjoABRcmQxoIDg8PDw4XCREQNSAfBJ4X5twCCAMEphfk3AIeFybEF87cAkg/ETtEMQYbEQ8OFxMFAxki"
  + "OR0ZAxkeDgYdQBECExUXWhA+CQSeGqbZAhAdBK4aitkCJw0ciBr+2AIRFwQVPRkaFSYIDBkcAlInCxcVBQ8ZHQMbHwSYGqLX"
  + "AgYZBJ4aitcCKRkc9hny1gIrCCspEB0pE5cBFAsdGiUXFwAfDgkJEU0QJxEEghes1QILAgT4Fq7VAg0OOuwWvNUCAxxtGiEZ"
  + "LQk5DndiDCgbDgYWOSAYHBcIK0IzBAscTSgjAAcWLQ0pCiYOIQ4PCxEUFQMHFHshAgsE7g/+2AIpCQTGD/bYAg0MFLoPgtkC"
  + "AxJJDgAQKCYQBwoiZxAMDBUQBMQOoNoCFhQE2g602gIYGCLyDszaAiciBhoZDAsoKAgKFhAHMhIgIiAEJhoaBhYRKgMWFhgH"
  + "BJIRqtwCDh4EhCWU1wJSDRzWJYjXAiAAcClALRQpfDM4ClgNejdcGUoARCQsABIWBOgsxNUCEggE+izM1QIcEySWLbrVAhYb"
  + "BRVlExMfCh0lB0IfBy0TF1hFaQ8YLRslLgMiM00hDTkEqCys0QIVCDqULLTRAh0DGRlFMhcPqwEQICAHGBUMEh4pLB0ESyG5"
  + "AQJHYCUIRR0RIRoPEx1JEHsDZRoFEB4MBx4VDmEOVQcEniK80wKZAQgihiHE0wIKKKoBPhAYGAMaGDEMPFAwCDoVIgIPKCY0"
  + "CzIYDBkYUiYE9CSC1wIQEgThCMyBAyogErcI7IEDigEIciecAxe8ATeCARBgHG5EbiAE3AGSggNOBCiqApaCAwQ7FiENEwwb"
  + "KAAQDwITPRFIKQk3KAkbLwgXHQsDEwwRJAMUExMxBKwDxv4CEREEnAO2/gIHDjyWA8T+Ah0ILR81BgsQHQcDDzcFIREdHDsV"
  + "Dx8xC18xPQu3ARgCExUTPzAZBCUFGxczAFMXRRYNDRgPHxdFDykhBLUG8vwCFQMEyQbw/AIfBDrnBvT8AlMiPRMbChUJIQgP"
  + "IDMIAw44IBwCOi4JDFAoUEIXBA4oCSg3HAcQKiQZGDkfZyovIgIOExAaHgccBMwTpuMCJAAa8BOm4wIuHVYLDCMaGRwMkAEN"
  + "IhEeO0QVKBICGBYGBIoYmOICFhIEoBiq4gIKGySqGJDiAg8NEiEqCAgNLAAQDwkXFB0gBw0pHDMuCSM5ABkMCxoECjUElBqu"
  + "3wIOAwSiGqzfAhkRHooanN8CNR8rCAYTFQcGFzcZKSglEw0hBhUdABkfACchNQTIF6rdAiNHBKARyNwCJxYW+hDe3AIHGhAK"
  + "HRoFFBJcSTwJHhYIHxYCFgSgEJrfAhMWBI4QsN8CIAourhC63wImAAgULTIsHiAFECQHDhoMEz4OFkA+FAUeJCAGFDoREBgM"
  + "RB9OAAIKJxgSLgTKE5jjAgIOBGeS5wI8GBArqucCBRoYCAscNAU0KkAKKhUEsgGE6AIUDATGAZDoAhYDJNwBjugCPCNwBhYR"
  + "IAAYDAYUIQoACjAiLikkEyAAAgxQCAUWGgpkCASqBrroAg4LBLgGsOgCCQ0isAak6AISCxE7Mh8aBiAPEDVTKScOCSMOES89"
  + "CyM5EgMrPxkHFwSGBZblAhEFBPYEkuUCIS0o1gTm5AIfEwcVGwIlExARFTkfBSMnTSUxBx8hHTkUQxcRGwBdUyMUKwMvGQQI"
  + "kuECBQsEBIjhAgIcTgak4QIvGkcCAig5EkMILQ0PHAoSHAcCED8QPCICHBsWEB4JJjUIFB5PLA0SLQMWIBwEKTIGIC0DChow"
  + "CAIMTgMiFjIDEB1EFiA0H0w2CgwOBFf+5gIRFCLJC4LpAjgUBxlCAkgXECcdBzMObS4tCRsIHyQyFBYFEBUnDSANGOsI5ukC"
  + "dC4kBQ4OIAAfKxwNLg4mCQoWHgMIDQSjBvbpAjQXBO8F4OkCABMq7wXO6QIOFREVPhsGFRwfHAsIF0oGOCVYGR4KChNQBAgX"
  + "UA8EExwIAxkaDwITBIkBmucCIgkEBIjhAhcXCBPy4AIWESsPCAsEH8rgAgsdBCmu4AIZAyRBrOACGRZBIycGOQ4fIj8YGwQR"
  + "Dyk0DCgJFkcYHQk5DgIgGwt9BgTPBZDiAhEoON8FuOICRVwvJpMBUAAUEQ5rIns8BUxuFhkoAhIcBRoOJE4jKCIEDBIPJhcE"
  + "DSgfICsOBw4dCRMUGjBWMATZCLbpAhMwHOMJluYCESB7UAAoGzAqB0IxRgsCNy4rFSUMFSUdEywEwBGE9AIyCiDyEY70AlQt"
  + "Qhg8KzAIMBUUEQUPLBECFxoHLBAHGC4EHB8mDASSFpTzAigMBLoWoPMCDgseyBaW8wIsRTtfAhtsPwMnLl0FRSYRDhsPIxIf"
  + "Hy8SIQkzBPQX7O0CHSME6hHU6gIhBgTKEdrqAjUCBJYR3OoCHwUE+BDY6gIPCjjqEOLqAgIcJggKDi9KEAgHFhY2NRoSGFsy"
  + "MiZFMh4ITEotAikUABQmLE8yGhgJIhkDHRZzGVkSEQxALgSyDsrwAgMqBLAO9PACEAAwwA708AISDx4KDBQXEhwIEhw6G1AW"
  + "PAAOGBkWGT5ULBIhJggJOgwUHwQDGhUaQQINIE4aBJYR+PMCKgwE6g6C5QISDhz8DpDlAkgKDhoiCDALHhcuDCoTCRNOCQId"
  + "LgQgKlQLBIQThOUCOCYEvBOq5QIeIQ7aE4rlAgVDIwAVLxojGgcAHwTUE9TjAgkvBI4QsN8CEQgg/g+43wJrHQASIQQXFzcL"
  + "CRMzBRkeJw4LFE0uMwYZDQ0SQR0ExAva3wIdAgSoC9zfAjEqKvgKhuACBggVIBgKAg57ECUSJhoTDisDAhgoEAAUFQUbEg4c"
  + "BxYkBjQyQRQcHASICvLiAiMSBOYJhOMCCgoq8AmO4wIGGCgGKg88OiYCBhgYDBoREA4kDxoGChYeACISLipIFAoYWhMEDhgA"
  + "BPAO7uQCBxQE1iCu8AIGEQTcIJ7wAiMVBLogivACJwoElCCU8AIAFgSUIKrwAhYFBKogpvACLAgE4CSU9wIQDUDwJIj3AkYA"
  + "BSk8BxQXJxkeFRIYGgIaMxoHDiMaDQcRRxsMERQEFiUTGQYLIAkmFg4jVB0yIAUdJgscGwwpMBwoBg4TBOop6PMCFAwE/in0"
  + "8wIaByCYKu7zAhoiNBkUNw0dDwIZITEEGSUeAxoZFDcaDBIHBTsVEQTgKtTxAi4NBI4ryPECDxMcgCu28QIRBAlJIRcMDRUp"
  + "IRMXLUELJxkJFyIJCREZAwSeKZjvAhcVBIgphO8CIwgw5iiM7wI5GUMJMxo5F2MGAw9rFQkPNQIrFRcOEBBbGiVAMQcTEj0I"
  + "FwoFIDsLBhhNDCcmBIwhqvACGwoE8iC08AICGhD0IM7wAhIQNTQrDRUqAxwQDAcQBJwg6PECEwQEiiDs8QIfLDbsH5jyAgwM"
  + "Fww2JAoeEx4sMBQCFiwQBAMaJiAZDCAMChIRDggaHgkqFgUeDA4VDAAaOwYAKBAQIgQE2CGg9gITFgTNHJT8AhgKbLUcnvwC"
  + "NgADMBwKBhQjFgYSKg4FFhAGOAcmGyACSiY+AxAWGggSISIUSg4KKR4NKAYIFykNJBdSDRMjOBcKGRgAHhkGOWQnABkWGxYE"
  + "BxY0BwMMSDBAFhgQBBo4CWIgFA8tKRoJMCA6Qx4DEgwJEAT3ENz7AioADM0Q3PsCAA8gEzAJAxUoFgTXD7b7AiIhBLUPlvsC"
  + "GAQmnQ+a+wIWCA4dDTsdHxALDTUSFSUHDBk9JykSOS8RCD0PAiElDQUhPRkE7RGS+AIFDQTxEYb4AhUCQIUSiPgCDw0zAwUU"
  + "IRorBicTLwASHSMdAhlRKysQEEQPDlsXNSQpBVseMQ01LFsHCyM7AxMPOQlJHkUXGQgOEDsOKwkEwxuy+AIrCATtG7r4AhoU"
  + "INMbzvgCFRYoNic2Aio1CAYkJBIjHgcaMiIRGhkDBBw1DhNABIYUwOgCERsc9hOm6AICJRQjHg8JLRATOx89TxcILScnBygj"
  + "CB0SBwSWE8DlAiYXBOoOguUCEw5G2A6Q5QIFFBIcDyY1DEkuURVLFgAgIgMEDBkgRRETEAIUIgwKEA0SGwADHA4KExYKEicM"
  + "DRoODicYDR4pBSsmFBYWAg0UFiYSCASkC+LpAh0qBIgLjOoCFBAinAuc6gJWPhYLAhdEDB4VKCAsHSAmDRYyBBYZWg4ODTYI"
  + "biEqDATSENTqAiYEBPYEkuUCGBssjgX45AJYAiIXGTMcGxgECBUeBiAoGBcyDkwFDAsAGywpHgo6FTElEBMcBhYVGAgEugmY"
  + "4wIsFQSoC9zfAicPIIILzt8CGEUZHx4VAA9PIwIdQREFExoNBxtFIRkZTw8IITsxBMgIrtwCFQ0EtAii3AIDEjayCLTcAj0S"
  + "GRg1AkUrIQIAEBUMEgoIGhMMAhAfChMTeQkHFBkKNQ0JFRkLHw5jIUUOCiAVDAYSFxoExALM3QIbDgSqAtrdAhkWJpIC8N0C"
  + "CyoUAyAWJRQrBAQPMyVXDD0JHRopADhCHyAkLgUSJjojLi0EBAXA4AIlEwSYNcrzAggPDqA1vPMCRAgWCQQXJA8nEyA9BJw2"
  + "yvICAx04mjau8gIVACcxhAEOJg0MERETNR81CQ4tSysZJ3c5AhEzGxYRDwsnDR0fiwEZQS8gJwUnGzMYDyEjjQE/sQF1BN4v"
  + "8OsCHBM8+i/e6wJbMjoqJShuNBoYSTxFIiELHRgGDh8UDhohDhAQDRCXASQJHhcbJwMLDiwWESQkGBAeCRobBAAOQyAAFATY"
  + "LIjxAhcYBMIsoPECIgA25Cyg8QI0GjwKUiw2E2QcJioqCSgqOAcIFhADNj5UEC4LDBE6ChQPHhIRFg4MHA8kBhgWRAAeFR4M"
  + "BI41vvMCCgwEwCXy4QI6Ckb6JfzhAhYNbjAUAwoXIgAWJz4OETE2AAgREyEWHQA1KS1OBBYVNAJYG0gwFgARHxw7ER8GLRVh"
  + "FAMVIUoTLAQCDSwPFB08BTIZBP4smN0CLAoE+irU2AItBCzOKtjYAhMgNQQALh8MEwtRGhMRVRAIEA0kFhxFHx0EERiBAS81"
  + "ADcjDQQLSCsWUwcEyCSg2gIfCgT8DPaBAzYMBLINgoIDBhEOuA3ygQMoGxBFGh0NGRsQNwAErg3wgAMHIQSoDdCAAx8XBooN"
  + "uoADE1EVEQTkDNr/Ah0lBMgMtv8CBwYOwgy8/wJ3IRkKDREeHwAnFAIE2gvU/gIEJwTeC67+AikFKLYLqv4CDw8YGxMdLQkx"
  + "HQUTEhk5IaEBCgkQHwQFJTsCLx01AwcLUQAPHSMJBLwGqPwCDwsErgae/AIhBRyOBpr8AhMKAhQXFB4WGRYICJcBQAIWISgb"
  + "E2MERR4EEgSGA6D+AhYWbKwDxv4CEjAVEiUCDRACEhwKCRYaLikICDZJKDwQAxIRDikADRoMEhcgBTqGARw6GiIHOCs2AyAh"
  + "igEOFhVcCwQxIwgXBQUPHg0ADSwSGCU2IygQCg4RDlYOAhAYEHAEFjAOAgIgRB5kBxoPSAIeHzYNBN4Lrv4CBg8u5Aug/gIe"
  + "BxYpDwskEwopERkyKy8vIA0JHTAZDhkwAA0fCAc4CRYRDS0cJxwFKB0iAATyDrj6AhASBIIPyvoCEiEQlA+q+gIPDzINCicR"
  + "FwoXFQsQFQS4D6D5AhIDBMoPnvkCBxMaxA+M+QIXDQ9DMScQBzc/exNZCiEJHycxDiMRDhUE9guI9wIHGwTwC+72AlEeLqAL"
  + "jPcCAyUhBxUMER0/AAkOJwcREiUNKSYFFi0IEy5hAhEONhQJDhsAPyEHDDcLDwgE7Abu9wIjBwTKBuj3AgoeCNQGhvgCPgID"
  + "DE0SBMQGpvgCJxwEngbC+AIgFCK+Btb4AiswCBgdJDIcQgZALgooFyIUBgoqLQ4QDFkiBRQdDAgOBLoG9vsCDSgK7ye0+gID"
  + "JCYKGhE/HwTtG7r4AkETLq0cqPgCWRsDFRELCBMWBwYbFgMkS1QIOhMQGRQFMhoUEwsPDhETCQI1LwUJGx8NJRoExRvq9QIR"
  + "D94B1Rvc9QIDDxQVESmPAQ45HhsRWwZVVi0YCxkMHUEJHxI3ACcPDRoXDyYfGSFXCx0KQQUTGh4IABwnRCUkVywfBhkNRR5F"
  + "AxEi1gIwRBUUDgwyFwgJIEEMCQxXFCkJEycjGQIoDRgUCg0QMwIoGg8iGhICLRALEgwQEU4MDA8cA0wWJAMKESYQaRIMFjUI"
  + "CRNDAAMWKioXCA0PSQllJ0cSHxlBAwwqDyAVCiI4EyIwNHgUFBIcBAQafgwOEkQWThswAyYmgAEEBA42CBAOEgcFLRQZLgwO"
  + "FywRCTwiEFYGIBMqBBIXBLscoPwCEw04/kKOywIUDS4ELBtMCwoPMgcqCgMdLC94MxYCBCUOBRIpKhUGNSAfPAQIYQsLIBkT"
  + "EwIjQgMIDT4iHgkEukmCxwIEJZgBvknexgINGQ4hCUsdDw4TERkRBBMTMQ0IGxYUMAkbJScPGzMKDz8pAhsYCSEpJwANEk0M"
  + "DBwHEhkDIxp3GgkOHwMHEjsWLS4SJkwQChYiFo0BFgoYDQYzEyUYLBwVGDwMDhIGJAsSFgYXIqcBFwYYFxwQEjQGCyBWHgMW"
  + "FQILIDUKCxAZAi8gDAgJKhceggEcAA5DIgQaDwwZAh0VCxAE6ELsygIWIgT+Qo7LAiIEXqBDkssCAB4wABI8CSYsCgogJA4E"
  + "DRwAEAwEHkQOBhCAAQo0GgkOICImEiwEHg0WDEo/ND4HQB0eFCgLHhoOCh4TMhQMNgAyFQ0XDhkakwEVGRthUm0QiwENLRxn"
  + "BY0BByeJAZUBEVMEtkmSxwIEEQSuGorZAjgXLOYa9NgCChOoAQ8YBgY2LgRwNUwAUCoIFhcCCDAcChMUFQIAFA8MFg47RBYO"
  + "JAMgKgSIH5rbAhYSBKok7tkCBBEeriTe2QIUEQIbHgIAFxAFD1UWGToPAg8wJwQdGwIAFSUfBKwlotcCKQ8EhiHE0wJBDAbG"
  + "INDTAjMkFhgEqiCM1AIlFlCGIKLUAggODRJGGBgeAg4hIgISFRwfBB0eIQQADjUaHQsNDgoWMxQDGD8FCQstCgcMHiILEhkC"
  + "DRg1BDMZCyUxBDEzGA0XCzEMESg1GR8ACBoRDgTgGojXAkMCBLoHjNYCGAMq0geK1gIODEQAFBAgES4UFhckBQQXjAEwAxAt"
  + "AxMQQgoNDhgMTgkWGhAPIhAIEgT8C5LXAhgFBJQMjtcCCxE2igz+1gIaNxYFBR82DwYxOiktEzQFDiEZBxMXTBsQEzYJEAsA"
  + "Ex4LDh0WC0oZFAQGFhYCChUfEQUVBN4PutMCEA8E2gbKzgI5DhKiBtjOAl8WMRkKIxsVJk0NE40BDA0LBIYExM0CKQgy3gPM"
  + "zQIGCh0SCCAJOhY8UhEQCB5AKBwdCgcQEAwVIkMhBSgcAAkYGxxbJko6AhY4CBcQVEAE/ASk0gIfCgTeBK7SAigCOIYFsNIC"
  + "SEAQByQuJBEOEGILGBcWAg4ZGBAJHhwEEjITEh4GFDwaDUImJAMCGBcUFwkdJCsCJyIOGGE6BMgH8NUCDxwETNDXAkAKJIwB"
  + "2tcCAxMaAAIUGBIiBkwdOhgYCwwOMAgSHE4FHAgKEBoDTDEeIATEBZrYAiIIBOYFotgCEhEk+AWS2AIEFUAaHhctCw4ZRTcK"
  + "GSgKHhEYCBoVBx0QDQUZHgkZHRQNBJoHkNYCIAUE3gSu0gI7FCqkBMLSApkBBAkWMQ0NBAAWMxAvEzMECR4VAxEiHAgRGA8A"
  + "GTQ5ACkaITw7AgURBE/G1AITCQRhvtQCGwQKe8LUAicHDQ4hCwcKBNMBytQCIQsE8wHA1AIHIDD5AeDUAh8ABRwmCgQSEQgQ"
  + "DgcQNBwjRiQCA0gpEjokCgleEiQmJhkCERcNMCEaAxAQESwEOLbXAhQaBKoC2t0CKw02gALO3QIfDBknCRQpDxUbEQgRDSgj"
  + "KAUbL0cpERsjBDUxBjESCxUbHiEFGRsGQxMJETQrAhk5IyEDBHnM2QIVCwSNAcLZAhsQOqcB0tkCDRQxAgI7MQ13EAccDDAv"
  + "EgMSLwIpEAsYZSIALjEOBw9bBSkVIQNNGjMPJwYcLg0eIwU9GBUflQEjBOcJtNsCAi5A5Qni2wIHIh4cJFQeBBYRPAlACgka"
  + "ISBvRA8TBg0vJRtFEQtkmgUErAEWKCw0IAMUGQAZ7AGlASQ7GmU8cUo/EhovICE0JZ4BBMEF5OECDywEhiCi1AIvBBbYH6bU"
  + "ApUBK3FLSRsCD0ELPSVdVVESLQd7OQTAGdzRAhkRBIYUntMCKgwasBSq0wI6IAs8KSgOEBESHjZMCSIhPhpcDgwIABoE6Bao"
  + "1QIQBgTNENz7AhMcCt8Q+PsCRAgsEQUPFBcE3w/M+wIIFwSdD5r7Ag8MFKsPpvsCQVQAElgqWgAMDSUjGiFIDXAGBP8M4vsC"
  + "WhAgpQzy+wIgGwMVGA8REyw7KAUUGTAHJhIQFjAOCBhCCBIPOgcE6wiK+wI8DwSvCPz6AgcJLrUI9PoCCjETEx4zCxESKSUf"
  + "FSUcPwcRFCMKPRoXCyMQFwUTMQ0hCDUZF0UVCQYXGyUEwQnY9QIXFwTXCcL1AgkjBN8JoPUCSRAgpwqw9QIrBh8eTQYLCQoT"
  + "lwEtKTclAiEPHQoVC10IWyMREGklBJsQpPQCGRUEsxCQ9AIREjbDEKL0AgoaEwYCHA0MGA4yAhsYLQA4HAIWIhQRCAASKQ8Z"
  + "JCQoQUAfBTsSMwkCJCYaSAwTEEUPACwE0RHu9wIhGASuCtLwAkwaFvoK7PACLhpMDRAeNAIAEjoDEBEyEjwtIAIEkA6C8QIg"
  + "DwSIC4zqAgcODoILmuoCNyYjCxMVLQgpDREWBLQJtOoCGwUEmgmw6gIgLhy6Cd7qAjsUABYTGBAGKx5ZBgceGwNJHhceDjgU"
  + "DhsoBIYHkO0CIwwE5Aac7QIQBib0BqLtAioEFBcmHBwHGSgiQhBOGhAPFiIqYhJIEygyEgAGICYECg4VLgTCCsDwAhUSBOYE"
  + "zvQCEhA6+ATe9AJGGyQMehsRGRQvIgQWHEgNBx8SBwoUFAQqLR8dHBkUKygXFRUVAhwxEw0SDx0dDh02HQwOMghGOQSOCobx"
  + "AiA1BOQGnO0CKRw+vAa47QIREgMia0wNRjkMExY1BwwXGAcAD2UDOxEHDUkUKxUZLAgaCxQMGA0KGwkbGicTIxIaFBMWGwsX"
  + "BAIOPQIETJTwAhcoBDa88AIMGiBC1vACDQgSFgZAKDAeDgIQIBIPBgAUEhIFHCYyBBoXECAiBOoB2vMCBR4E5gH48wIeBBKE"
  + "AvzzAnYtGAonMCAOHBcaAgYSngEsBOYEwvQCAAwE+Cuu5AIACzL4K6TkAnCFAQQjKgKAATMJHBgwCwoyECwTAxUqEVIFLikQ"
  + "KwsjNR8IGw8TJDkTIy4KJhcUCBILBPow1OACBw8ElCW24gIAHgaUJdTiAg0aDgoEliX44gIDGASUJZDjAhQDLKgljuMCBhJW"
  + "NAUOOSIUEBgLDBAmDGADBhQiCQMWGBxIKhwAIx4hAgAaGwAJGh4JBOIn2OUCDB4EjivI8QIOFQqcK7TxAigRAg9EAiIUBKws"
  + "rPECFg0E+i/e6wISDQaMMNLrAlNTDBkExi/o6gIXGQS+Ke7qAg4QPMwp/uoCMgMqDgkaMRYKOiQCDCIYFhsQBhQbDAwKDyAh"
  + "AgQWGBA7HAUQUhQmBwweOwwCFg8EGwslBhUwIwUPDASMKeLuAgUiBPMBwNQCIwBElQLA1AI9I0cSLxMNEB4OERBtNwsQIRVH"
  + "HB8HExUzKA8RSxcpCDcTGwgPBwUdUQ5ZHQMQIAInJBsAXTFRBTEEMRYNFBsPFwQE9QuK1AIgKgjVC7TUAjJcftIDJr4BBP8J"
  + "oNoCGJQBBI0BwtkCChcQgwGs2QIANX4DJhVmBwAPIxcpWQQ+4NcCDhEE8Avu9gIsCDKcDPb2AgIRKSEADTgdBhs1JQMVJiMZ"
  + "ETwlEhpWHRxHKgtABgMcGg1ABgoVOggGCowBCTYIJikEwBGW9AIAEwTmBM70AiMSIMQE4PQCIBAIFGgyMioRNBYSHgAIGBwI"
  + "HTAOBggaKxAEIioABMwGyPcCAyAEvB7E6QIKEyDGHrLpAhUtUg0KGzAHShweFTYDBQwYBhARIgYAGxgDChBGGASKIvToAhoY"
  + "BKQijOkCIhNOxiL66AIbDSoXHSEfDjsVER0EFxkbIQM6Lw0PMwQwHwUNNBsADRcNEhs2ExUlACsbCxgXGAIhURoLEh9wPS4M"
  + "Og8KGSQYDBEjGwwrJgkWEBIJBIQlruMCEB8EhCO04QJDKCbCItzhAjERDRYIFCMQIhQVGCcIJQsvHk0HBBUhBj0fExAdHR8s"
  + "MQAXIQTMHpziAhMSBLoeruICCSQmsh7S4gJGMhgyFQoTKAgMExRLLicKMToGEBkoHwoEEisSFggURhYQHyQEjB3i5gIfCASW"
  + "HsjdAhsEHPwdzN0CBhQpDjs4SwsRLh0GIQUHM1MDHQ8lLCdmEwUEuhqY3wIZFASgGKriAkADKuAYqOICejIQEhIPIBAWFVYA"
  + "JhoSGywJGBMCExwVLhgQFhoZQgsSBAUQEhZCJQSeHqziAhwCHpsT2PICIh4YF1gIAxY0HBIVNhIGFR4EAxo6DAc4EgwCFASl"
  + "EIb0Ag8KBN8JoPUCChNW1QmO9QITGToNBhcQBwkbFg0CFRQRJgBeHy8bDBEFKyQRKAIAGQ4PCSUMIxkNwwEHDw13ESUVCRMq"
  + "BBYLABUcGxgJHgwSDQkVGCMNFz8fDA8RE0gJGBseBwMXBN8IwO8CHwsE/Qi27wI1CkKxCcDvAkUsFw8FH0UAEQsOGQ8REgkN"
  + "H1cbDwYOFhMaADIZCjkZDg0NGzZfMRl1DhkQIQchLk8CAxYpAC8WAhAdAhkiDQAEvQ+07wIZIiTVD9bvAjMgrQEkABY6Dgos"
  + "FxYKJBMMcy1FKh0ELRdJGAwsFR4lEGw0BJMTwvICCRYE+Bak+AIkDTCcF5j4AjoTFD8mExApFAkEJXlLAyEYBwAXEwMMMSUA"
  + "JxVfBwkjCg82FQYXJBkTCwQhFh0EkhfY8wIOBwSgF9LzAhMNCI4XxvMCLQg5DwsPBKAWsvMCGhMEyg+e+QIyABD8D575AggK"
  + "gAEQFiAkHToJIBokGQS8Erb5AiYKBOISwPkCFBcg9hKq+QICJy4FNj8TJxcIGR0eC1AOiAERMhYPDjgIAB0WCzAaBLQWnPgC"
  + "RAgE2g602gI5ETqiDqTaAiMKExcTDjkNOy0bCAAULwQSNS8XIS4lChUfYzMNFD0MABAUCgcgPRMrBiUcJwYJFiEQLhIGFB0A"
  + "BNII6NoCKw8EqAja2gINDhCcCOjaAgYkJRACIA8EBhojKFoWBLAImNwCBAoEqAja2gIPESaaCMraAmUDHxgXAwsRCBUbJRoP"
  + "FAYiHS1NLwcHEyIbFRdJFAAfKw0RHQTiBazYAgQLBNcJwvUCKA8irwm09QIuEx4GkAEXFgYFHHgtABAYBEojWAUsAhoWNAkW"
  + "JDgfRA4EgwOa9QIECwT/ApD1AggVHvcC/PQCiAElJBYUDycXGis6DxwWJAJECzgrQAAYDywIAhAEugGA9AIsCQQ2vPACEwUM"
  + "JLjwAhEQHxMjQSsIDQsEY/TvAgUdBGfY7wIbCyaBAc7vAhUQHwAaHiEIEw0pCnUNKxlBAwIOIwBBFQcrMx09CikRSRRFGwTZ"
  + "BoTvAiUFBP0GgO8CCxIIhweS7wJjGhERgQEWBPkIsu8CBQQEyQbw/AILFxDTBtr8AiACGhs4FycbFiUXPUspBNEGivsCDRUE"
  + "3Qb2+gIlCQqBB+76Aj0WERchBTkaBKUIhPsCCwkEpQzy+wIcBnaJDPj7AkIPVCBzKhkoHQQPEABGHxAQCBI2EggIGBMKAjwj"
  + "FBE6EDQPQBImGwMRE1FwNSYtCC2KAR8KBRQsIAUwDx5XGAoUDQoGFjwVKgYSFzALWAcOESgCCA9oDCIMDhoyCJoBCQURIB0K"
  + "LRkEDRUfCQsvigGDAQYREQ8ODQSNCdaBAywLBNYm1IADFAAs6ibUgAMYGzcZNEkONycnKAwcCwUfHQsiCwkTLRkzCxUXFD0x"
  + "FwIVLAk4MRQAAiUElCfC/AIZFwT8Jqz8AicEFtYmsPwCDwsbCisVVwILD04RABtRGx47UwwE7iSe+wIxCwTkG+z7AiUOGMAb"
  + "+vsCAwpPFB4WADQbAw8UIwQOGCACCxo0DgScG7r9AgIaBPwmrPwCFA8akCee/AIRDQ4ZDQ0UDSQWFCWKATtiFywjOBECFSYV"
  + "BMYqqvoCGAcE3iqk+gIbCTDEKpz6AiUdIgUXEwMXGAUoFCgRQj8YDioZDxswCSAXChcxDwIfNz8eAHY1ECsRDQobPgoE2i3a"
  + "9gIiJQT8Lbb2AgYRLIIupvYCJwUvOy0MEw0CGS8AExMDJRoABBkbIwYdXw0LHBMGJyMxDCUPKQQAHSEdBP4pgvQCAA8E3Qb2"
  + "+gI+JTSfBtL6AhQAAxUWCyoMFQ4GChwFJBIOKzYcMAIsID4ITBceCBIWMA8eHhUKOA4+IxcNFj9cAAcbBDus+gIELwQ3/vkC"
  + "GQ06T/L5AiMEGw0GExkHEi0ZIxA3aTEFFyYXFx0ODQcRKwgvFRcjGAciMTkbOwcLIx4FAh8lACcbDhcuBQwnBPkCmPUCBwkE"
  + "3iraggNIEhKmK+yCAw4OJglGHiYNSBY+FQAXIhcE7i3aggMYA3iGLtiCAywXBC0fFxIHAiEYCQYTEwsqHRQCByEcHQITKxUH"
  + "GRQAGBUtFxYfSQUJEx4nXCkDJSYPIgQQI1oEGA8aChATKAsfGw4RGRUyCwkLKCkYCygQFBkkABYTNAIiIygPFAYeGUYVGBc2"
  + "AggTFAcqABgQHh0WBDQhGB0Ekjeo+wIWEQSoN5j7AhENBJg3jPsCEA0EqDeA+wIsAgTUN4L7Ah8DSLY3gPsCcSFZPR0MJxEN"
  + "E3UQNRQZKCkPERcQFTMOIxOpAQsbCgUQIQULFR0HVQQEGSUbExKLARcRGgoMEw45AhUMJh4NCBIaEQ4hDEUZBJwt4voCFw4E"
  + "hi3w+gIFGmaCLYr7Ag4UPRQCHDYeHSIUMDMqHAgDFBwSDi4RJhoMLR40HjAGLSISJCAULyIODAUYLwcbEg4aEQYWKikDBxQU"
  + "DhUSChYeCggYJQgLFBAUMyoEFjsWHRMlBEURCRMdBioaHQQEFhUiBhAEkirSgwMkGwi2KriDAwwrGA0TFQTIKu6CAxYVBIYt"
  + "8PoCHR8O6izS+gIZByMMQSE1Ai0LCw8Ehiui+gIpAgzfGoT0AikALxQMDkINCBca+xiG8gImBRAhUhMTGRUFSRI3CR0WCggV"
  + "MCgIGg8EmxPY8gIXBYABsRPU8gITDggQDRA8Bk0eGwMJDTUEAA4xCh8tIwpRFTcMAg4dFicKBBAcAhQVOAwsExwQFCgtFAQY"
  + "TxcVBiURBxctDg0RNw8XEkUVHwYLJxIlFg8lCRceABgSFAcgExo1IgIYUCoCEjMKAiEtIwQXSzY1CAkUKRtBB0U+CxgMGBMK"
  + "AxQE0xvc9QIODgSGLtiCAy4EWLQu3IIDIAkKKY4BFiAeZAYYBxAZRBU4DjINVC0PETATFSlGMThRGgYMERUTGhkuBDIRGhoZ"
  + "ImQKGBMOBjwVBxUaOzAcNhNaCCQPMBwgAgQaUAwKEyYEAx0kLWgdBNA7rv8CBBFa1Due/wI7YS0ZUyJ/GSEcOxAbCSUaLQMb"
  + "RiUJChEZFRdLKwQNGxcNCBNQHwYPIAQEESMDAiEaAAgXOh4EFi4FAA0gACIfHgUOGS9NEwMWHygDIx8IBRcnJyUzGTcKBMo3"
  + "mvsCIwMEoBfS8wIqDUDKF8bzAlQeQEcmBCAhMg42GygKEhRaDwRCDAMKH0IfACNiEyQpGgsiCiwbIjgaBxAVHw8IHyQQJAMW"
  + "DwgjGhUcBBIYBM4f7PECPAAE8iC08AIdBwSUIJTwAhcHKv4fjvACIQQZKx4VDzE7GxIPGg4QHxMnPjstEQY3YxknG1MVExEd"
  + "Aw8iMRBjCwS2HJbtAgkIEOAX8IcDGA4eDRsPBBFJDwQgJAoElBC+jgMqAH6+EL6OAxwONAMCEJYBGDYJlgEmHFUiERgrKxsS"
  + "CQIzGDNUAhQhTEMiBjIdGAgQKFQeQgIWFCoNPEUgAA4PBBcVFShRBDNaJWIqLg0ZGXAAOC0KQRETECckHxYIBCAMBmgCOhl2"
  + "HgoRVC0CGVQDDhE/NwcpHRtIAAAbHh8LFTkNGx0WIQS+IMSGAxMLBOQY3IYDNxAErhjshgMdGgSSGIaHAwQeapYYpIcDFAgX"
  + "HEBAGRAKFC4INyZTCiMNAxREHFE2Dx5WLBcQEQ8XBgAmNRpDCxMOAhQ5CxkIDBAHHhMENC4cAj0mKQcNLyEFDRJVDy0UFw8b"
  + "BgUOJw1ZKBkAFQwSDCssSBolEn0EJxxPlAEnIh8IBPgN3oQDGAU4kA7ahAMcDwIhOAsoFrwBISIOoAENNiNMBSAhHBBCJzQM"
  + "Bh8UCRQKEipuBwkUChgsBQ4aOhIiDSgSJB0kIAT2F7CEAzgHBIAY3v8CGSEW6Be+/wIpBiMTSQwvEQsONwYFDyMRMQZJKgTK"
  + "FNT/Ai0dBJ4UuP8CIRIo/hPK/wJFCA4MIRJ/GiUYGRsjCSMcJQczEiUDFxJLIRsIWRdbGCkNDwYJKgTGDcaAAx8KBLINgoID"
  + "CBgsug2aggM2Jg4gEwgXER8MHB4VBAIUEQ4JHhAQDxgSGhoIExQfFQ8OGg4EFhoIBQ4Ezg3YhAMqBgSeBsL4AiMNMPwFtvgC"
  + "KRAdJiscHxNZBAcQJRQHFlMGGRQLTAoQGyA5FoEBERUbJQMRGyEFBxcrBREQMREELfz5AgsCBJIYhocDEQlcghj+hgM9DiUP"
  + "IwgbEysGEyRfKRcKKCwTEiMQJyM7CA8MLQIEDhcOGxsTGCEDIQ8VJTcWDi4YElIULSAvCCUZHxQnEyEQGREdBjsXJw4lCR82"
  + "eS4WChUSFRNxMIkBHR0UBOoMsIkDERQi2gzEiQMvCBkSHowBIgMtJABIETgiIgocAiAdPAYSOgZWPDQQigIsBP4Pto4DFggE"
  + "Yb7UAggZPFmm1AIwLwsVEBMhCwUhHBcaIhoXETEkHRUVIwQXHwIPGhEdJxsJBC8zAh01LRELRz0FBR0ZBQZJLxMULwcVBLsC"
  + "4s4CCQ1ywwLWzgIbAy0lEwgjDUMeDRsXBwkREwQCGBkDDRxLNDEICRQIDBsqOw85AyMMLwk9Ik8OHxQVDSEaDwUxGCUNLRgc"
  + "MisHGRUJQVkSHS42JAAWICoCPiEUGQlFGjsFBg0VGx8CFyAIEC8OPxMdMB8IABaUASJcWASNDOjTAhgiEGnq0QITAhMcHCYU"
  + "CwUPEBkZFRJp3tICFA4WGw8nIwQHFBwCAxgPAATeA8zNAisLKLQDws0CIwYLEiEKIxMHFx0LISpVFEEbFwgtFxcGIxMzCgkY"
  + "IwQ7TBMNYzIElQLUzgInDgTkF9bOAgUnWuAXsM4CA68BDE0kGzQLEQkMGRQFFCs3AiMNLzBJCRUQGRlTACspHQcTDlEXExEQ"
  + "L18QGQUPFTsGMSYCCrUBMjcXLwgdDQ0fIRVjABseAyARBgcYMwVTKEkCBxoKIBIOBNoNxMwCIAoE1Due/wImCUL6O5b/AmAC"
  + "GBJKIRgOGAkSEi4hRg0qGYIBDwoLJQs5QS1TQxkbHSMDByNLOzMXKUEIOSkhBSMdNQUdDikNEx8LJVVDQwUZBK47hvgCFQ8U"
  + "mjv49wI7BgkaIwQLDAgkfywbAzE8IwUEyjiu+QItCASeOLb5Ag8aDpA40PkCQQMrEh4YDTQUOBMEBLo36PoCGhoEmjv49wIC"
  + "Dz6cO+r3AglNIhsQIScpAB8dFwgdIUMMQR8VCCksHxolCRNPIxQZEwUDFRUPNRANDxwJHx8pDysIXRMPED8GEDAdAwT2N4Lz"
  + "Ah0OGto3kPMCBiAfEBUoFwonCxccKjQVHAwWYzJPDg8QBMA1uvUCAxQEvjXO9QI0EBryNd71AhYMFSocEAkiGDg6GBwyEggk"
  + "MhsIPEY2WgSEOKr5AhoMBKQijOkCBCwmqCK46QIOIFIJEBUiAhQYHBsgBQAQJBgiAxQTHRs4GRENEA0REQoRHAcEliXc6AIW"
  + "BAT8Lbb2AhASOIwuyPYCEgQAEhIMGA0XERANEBQYAB4UEhpaFBgTDDcaAg4PHgkoFi4FKgxCEyw1QgoWHiwMJCeMATkIFQSI"
  + "Ndb1AiARBKg1xvUCDRMQnDW09QI3MQMZEA0ELRohFwsYLQSUNd7zAgQVBJI10uUCBjVAmDWe5QIoJToRBQsgESAGIg8XMxIP"
  + "BEksBwIVNgkOJUYbFy8ZDQUTFQUYSUcvERBXEw0dOw0NDQoTLwtRIB8ZOwQJEQSQNMTgAisPBMgt8uYCHgc+5i3s5gIMWygn"
  + "MAgSEQcXRCMKCB4JPBY2HwcfKgAIEVgIOFQoGi5QLBQsCw4RBQ8dAwwlMh88BBodBC8UBSwsLgwExC606AIeDGDiLsDoAjwF"
  + "BgwoACINMhIKFDIcKgogHAMMKQkfHihGGhIoBAwTIg18QCALsAEORBEQDSUbDhdQMwsdMzMIFRUXBBlmERtHEAkkFhwRIC0m"
  + "GwUVFAcGHxkJHTEpCQ0PewsPFQgJBJw18OUCCx8E8BLS/QIuCQieE8r9AgAXPwolDwS8ErD9AiECBJwSsv0CNQ4I6BHA/QI5"
  + "FggQLggE5hHu/QIqFgSQEoT+AkICBNIShv4CHCEE7hLm/QICFRDmCpKHA04FCRdAHU4/VCEgHTBvBN4N9IQDGhdI/Az2gQM3"
  + "DB8eSQMbDmUGRR8DIQ8DFzFxBRkRAxFXDxAPCw8pETciGSQtEwAMHwwEDhYEIgkFMF0KFxQfAm0RISA3AjkqIwY7G18TBNIC"
  + "oIIDAgog1AKqggNVBYcBEjUqBB4+UhxEHBSAAST8AWzaARquASw4BVYUZCZ+SgS0CoCHAzISBIwUtPwCBRAEiBTE/AIoQgSw"
  + "FIb9AhEiBKAUqP0CABIOoBS6/QIZKBQcBCADHBMOCBgElBTg/gIbEgT6E/L+AgcOBvQTgP8CKBoRDASMFKb/AhISBNYahvoC"
  + "HwoeuBqQ+gIRBwMXVQYdDXMGKw8xAg8VBgsbFxwlJ0EhAykdBPYWsvgCAg8E4hLA+QIYEhz6EtL5AgQYYjYVDgc2DhYRFBQk"
  + "AxYaFBMKCCwKDioIBJoUqPwCDwwEmBGM/gIhDQj4EID+AhEXADkyFQSaEZ79AhgXBLIRiP0CGQUgmhGE/QJFIyUFDBUdHSUC"
  + "HS8qGRsPES9RBAUPIg8XEw0jFQkE+g7a+gIIEQTIDLb/AiYEKu4Muv8CHAUyIyQUIgcCDiIEJBMPGRIRFhYUAhoVNgAgGTwQ"
  + "LAUJETgXAhMcBQSeEbb+AgcrBGfY7wIUNVpTpO8CEBMcBQchIjMTHTYdCxMZDicRGhUGOTQZJxEHIz0zWBMDHR0TEBURGRkA"
  + "CzcYBggdCSU0JxUREAkCFy4ZFBooFCYTBxcTBxQbDQ0hAhAnHxMHG1AnIAodLwTAAaDoAgYRBO8F4OkCHANE0wXe6QIYGDIJ"
  + "DBQgCgAOKgMYGkkcCxkVGgQQEgYCGAskFQosGgUcExAMChESDg4VEgUYKxgYDg0SPTIUNksUMyoOFA0eKwoE6Qbg7gIVIATm"
  + "CpKHA0gsHq4LvocDHD4eHiQOMB8gBC4RCgoXHikCHygrBA0WDEQ+CgTMDLiJAx4JBJQMjtcCEgIwpgyQ1wIHGB0CGhQuByYy"
  + "FgAgIg0SHQYGFhEGBBQwAkAVJBwUEw4GCxIeCjwAGw4aBjIVBLIP7tgCFAgKojKI0AIkHhQFFRslAAj+MfDPAhEUJgIXFwzk"
  + "MIzQAgYVKxEtEiYDKhQE+izM1QIEBgSWNtjTAg0dYoo2vNMCHxkjAgARTQURDiETGT8fBQ8XUykCDzYKFgsQDhQNIx0GITMv"
  + "HRolAj0lWwUnDQMxXSBDBTEbCx0IIysMEAgHHl8AGxpDBBUQFQsQHS0TDxcfBBkcCh4pCggMOQYHDBsFBL4siNECFyQanCbM"
  + "2gIaLEYQHCEgCwQTGQMzQVkGCRQODhkMFA4MgRL27AIhFx8IIR4aBkQXBOsI5ukCJwookQnw6QIjBQcziQFMewAlOG8QYSRH"
  + "KiUEK3BVVBsAERyhAWIPSCICEhwuHhw6BO8PoO8CMhQclxHo7gIbDikHJx4KFhAQGgAgFQkhRBsKEQAXFQUfLASaCbDqAhUE"
  + "GoYJtOoCIydLDBkTBSMjH1kGDxUZBQ8jJwAPESYvBMIG1ugCCycEvjXO9QIXCQTaN5DzAhMLCsg3hvMCWQonDQwpHQcEujbW"
  + "8gIfDQSyEYj9AgYLBrgR/vwCIAUyIQSKEtr8AgYSBJAS7PwCIgsKshLi/AIQEywDWhIyMQT6E7D8AhIEBPIRtv4CJAUGlhKy"
  + "/gIKDxERBJASlP4CABEEnBKy/QIPHwaOEpT9AggHExsEhBL0/AIMCQSYEYz+AkQmBNwRsv4CFgQEoBSo/QI7JgTmE879AjUQ"
  + "BLIT3v0CQw0E8hG2/gIIEBD6Ecb+AiQLCgwoAhgPNAA2GhIYBOQT7v4CFgQ=";

/* Pour chaque département, le nombre d'anneaux, puis pour chaque anneau le
   nombre d'arcs et leurs rangs signés. Un rang négatif se lit `~rang` et veut
   dire que l'arc se parcourt à l'envers. */
const INDEX =
  "wAECJgACBAYICgwOEBIUFhgaHB4gIiQCJiYoKiwuMDI0Njg6PD5AQkRGSEoCJExOUFJUVlhaXF5gYmRmaGpsbgIgcHJ0dnh6"
  + "fH6AAYIBhAGGAYgBigGMAY4BAhqQAZIBlAGWAZgBdXOaAZwBngGgAaIBpAECDqYBqAGqAawBrgF/fQIosAGyAbQBtgG4AboB"
  + "vAG+AcABwgHEAcYByAHKAcwBzgHQAdIB1AHWAQIU2AHaAdwB3gHgAeIB5AHmAU1LAhToAeoB7AHuAfAB8gH0AfYB+AH6AQIe"
  + "/AH+AYACggKEAoYCiAKKAowCjgKQApIClAKWApgCAiCaApwCngKgAqICpAKmAqgCqgKsAq4CsAKyAu8B7QHrAQIqtAK2ArgC"
  + "ugK8Ar4CwALCAsQCxgLIAsoCzALOAtAC0gLUAtYC2ALaAtwCAhTeAuAC4gLkAuYC6ALqAuwC7gLwAgIU8gL0AvYC+AL6AvwC"
  + "/gKAA4IDhAMCJIYDiAOKA4wDjgOQA5IDlAOWA7sCuQK3ApgDmgOcA54DoAOiAwIepAOmA6gDqgOsA64DsAOyA7QDtgO4A7oD"
  + "vAO+A8ADBgLCAyDEA8YDyAPKA8wDwwPBA78DzgPQA9ID1APWA9gD2gPcAwLeAwIk4APiA+QD5gPoA+oDcW9t7APuA/AD8gP0"
  + "A/YD+AP6A/wDAiT+A4AEggSEBIYEiASlA6MDoQOKBIwEjgSQBJIElASWBJgEmgQEDJwEngSgBKIEpASmBCqVApMCkQKoBKoE"
  + "rASuBLAEsgS0BLYEuAS6BLwEvgTABMIExATGBMgEygQCGswEzgTQBNIE1ATWBNgE2gTcBN4E4ATiBOQEAiTzA/ED7wNraWfm"
  + "BOgE6gSFBIMEgQTsBO4E8ATyBPQE9gQCKvgE+gT8BJcElQSTBP4EgAWCBYQFhgWIBYoFjAWOBdUD0wPRA70DuwO5AwIUkAWS"
  + "BZQFlgWYBZoFnAWeBaAFogUCHqQFpgWoBaEBnwGdAZEBjwGNAaoFrAWuBcMBwQG/AQIksAWyBbQFtgW4BboFvAW+BcAFwgXE"
  + "BcYFyAXKBcwFzgX9AtAFAirLBckFxwXSBdQF1gXYBdoF3AXeBeAF4gXkBeYF6AXqBewF7gXwBfIF9AUEAvYFDucE5QT4BfoF"
  + "/AX+BYAGAgiCBoQGhgaIBgIIhQaKBowGjgYCJpAGkgaUBs0BywHJAZYGmAaaBvMC8QKcBp4GoAaiBqQGxwLFAsMCAiamBqgG"
  + "qgasBq4GsAahAp8CnQL9AfsBsga0BrYGuAa6BrwGvgbABgIkwgbEBsYGyAbKBswGwwbBBr8GzgbQBtIG1AbWBtgG2gbcBt4G"
  + "AhrZA9cDkQWPBY0F4AbiBuQG5gboBuoG7AbuBgIapwalBvAG8gb0BqsCqQL2BvgG+gbNAssCyQIECPwG/gaAB9UEIoIHhAeG"
  + "B4gHigeMB44HkAeSB5QHlgeYB5oHnAeeB90E2wQCJKAHogekB/kD9wP1A/kE9wT1BKYHqAeqB6wHrgewB7IHtAe2BwIeuAe6"
  + "B7wHuQe3B7UHvgfAB8IHxAfGB8gHygfMB84HAirQB9IH1AenAaUBowGrBakFpwW9AbsBuQHWB9gH2gfcB94H4AchHx0CIOIH"
  + "5AfmB58FnQXoB+oH7AcLCe4H8AfyB7sEuQS3BAIa9Af2B/gH+gf8B+sG6Qb+B4AIggjhBt8G3QYCJOsF6QXnBYQIhgiICP8D"
  + "/QP7A6cHpQejB78HvQe7B4oIjAiOCAIqkAiSCJQIlgiYCJoI3QfbB9kHtwG1AbMBnAieCKAIogikCKYIX11bAh6jCKEInwjZ"
  + "AdcB1QGoCKoIrAiTA5EDjwOuCLAIsggCGrQItgibB5kHlwe4CLoIvAi+CMAIwgjECMYIAirICMoIzAjOCNAI0gjnA+UD4wOL"
  + "CIkIhwjlBeMF4QXUCNYI2AjaCNwI3ggCJJEEjwSNBJ8DnQObA98C3QLbAuAI4gjkCOYI6AjqCIUFgwWBBQIkiwWJBYcF7Qjr"
  + "COkI7AjuCPAIyQbHBsUGhQiDCIEI5wblBuMGAh6vCK0IqwjTAdEBzwGXBpUGkwbBAr8CvQKZA5cDlQMCLJUH8gj0CPYI+Aj6"
  + "CPwIywfJB8cH/giACYIJhAmGCYgJigmMCY4Jvwi9CLsIAhqHA4UDkAmSCZQJlgmYCZoJjQeLB5wJngmgCQIk6QHnAeUBogmk"
  + "CaYJqAmqCawJiQKHAoUCrgmwCbIJLSspAiSvCa0Jqwm0CbYJuAm6CbwJvgnACcIJxAmvBK0EqwSPAo0CiwICHp0JmwmZCcYJ"
  + "yAnKCcwJzgnQCfkI9wj1CJMHkQePBwIa0gnUCdYJ2AnaCdwJ3gngCeIJ5AnmCegJ6gkCIOMB4QHsCe4J8AntCesJ8gn0CfYJ"
  + "uwm5CbcJqQmnCaUJBgL4CQL6CRr9BfsF4wThBN8EoQefB50HuQi3CPwJ/gmACgIOggqECoYKiAqKCt0J2wkCLNUI0wjRCIwK"
  + "jgqQCscExQTDBJIKqQSnBKUElAqWCpgKU1FP7QPrA+kDBAKaChKcCp4KoApDQaIKpAqmCqgKAiSqCqwKrgo5NzWwCrIKtAq2"
  + "CrgKugq5BbcFtQW8Cr4KwAoCJIMDgQP/AtEFzwXNBfcF9QXzBcIKxArGCs0JywnJCZcJlQmTCQIOqwqpCsgKygrMCs4K0AoC"
  + "JGVjYakIpwilCLUIswixCI0DiwOJA4sEiQSHBO0E6wTpBAIU2wbZBtcG0grUCtYK2AraCvkH9wcGAtwKAt4KFNUG0wbRBr0G"
  + "uwbgCuIK5ArXCtUKAg61ArMC5groCuoK8wHxAQIa7AruCvAK8gr0CvYK+Ar6CuMJ4QnfCY0KiwoCFPcK9Qr8Cv4KgAuCC4QL"
  + "hguIC4oLAhiMC44LkAsnJSPjB+EH3wedCJsImQgCJJILlAuWC5gLmgucC6UFowWhBekH5wflB7UEswSxBMcJxQnDCQIyowSh"
  + "BJ8ElQrBBL8EvQT1B/MH8QcHBQOTC5ELjwuXCJUIkwhZV1WbCpkKlwoCJMkKxwrFCvEF7wXtBZEIjwiNCNEHzwfNB/8I/Qj7"
  + "CNMJ0QnPCQIangugC6ILlQGTAdcH1QfTBxsZF6QLpgsCDqkLpwsVE6gLqgusCwISrguwC7ILtAu2C7gLugu8C74LAhTAC8IL"
  + "wwrBCr8KswXEC8YLyAvKCwI8zAvOC9AL0gvUC9YL2AvaC9wLtwq1CrMKMzEvtQmzCbEJgwKBAv8B3gvgC+IL4QjfCN0I5Avm"
  + "C+gLAh7qC+wL7gvwC/IL9AvZBdcF1QXFBcMFwQX2C/gL+gsCHosJiQmHCfwL/guADKsDqQOnA88DzQPLA4IMhAyGDAIeiAyK"
  + "DIwMzQrLCqcKpQo/PTuxCq8KrQrFC8MLAh7TAtECzwL9BvsG+QanAqUCowKzBrEGrwaODJAMkgwCJOcI5QjjCNkC1wLVApUM"
  + "kwyRDK0GqwapBs8GzQbLBvMI8QjvCAgClAwClgwCmAwWmgyFAYMBgQGxAa8BnAyeDKAM6QLnAgQCogwexwHFAbEFrwWtBYsB"
  + "iQGHAZ0M5QLjAuECnQabBpkGBgKkDBqRCY8JjQmJDIcMhQzJA8cDpgyoDKoMwwjBCAKsDAIkhQmDCYEJxQfDB8EHswexB68H"
  + "rgywDLIMsQOvA60DgwyBDP8LAiS1DLMMsQytB6sHqQfzBPEE7wSdBJsEmQT/BP0E+wS3A7UDswMCJvkJ9wn1CekJ5wnlCf0K"
  + "+wr5Co0LiwuJC7QMmQuXC5ULwQm/Cb0JAh7lC+ML4QubApkClwLNBMsEyQSTCpEKjwrPCM0IywgCFrcMhwuFC7YMuAy6DJUF"
  + "kwWfC50LmwsCJLwMvgzADMIMxAzGDOsL6QvnC9sI2QjXCN8F3QXbBfcL9QvzCwIiyAzKDMwMuwu5C7cLzgzQDNIMwwzBDL8M"
  + "8QvvC+0L1AzWDAIe2QvXC9UL2AzaDNwMwQu/C70LzwzNDMsM3gzgDOIMAh61C7MLsQvfDN0M2wzTC9ELzwvJDMcMxQzVDNMM"
  + "0QwCIt8L3QvbC+UM4wzhDNkM1wz9C/sL+Qu/Bb0FuwW9CrsKuQo=";

// Les codes des 96 départements, dans l'ordre de l'index.
const CODES = "01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28,29,2A,2B,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95";

/* Les côtes d'Europe autour de la France, 30 morceaux, 684 points. */
const TERRE =
  "PDrKGO62AmAjZB42CTQRDkGrAd0BMV2tAVWtAUJlEh8YGWQvIEMOhwFPKzRBChkgAiqcA/ABeDb+AT4oCSMnIiMJHSEbDS8i"
  + "oEuyvwIyQXCHAgw5NWVxhQESbShFBktbmQU3vQFNG98BTHMVXywjxQE5UVCUQ7SwArMB8gETlAIwUA5WC0oUGiYbHgoIbDU6"
  + "WRQAeDAoDjQCogE/PDmUAaUBmAELeCyOAVY5Ng1oDWgQ+gFksAGgAW4gOCwSOC4QODlCB2ovUmFOJQYPIQ0lPU4z8gLPAYam"
  + "AyZRnALNAlEebwTFAVzBARXHAQiuAR/AAQOmA+EBjgGFAVaxATtP/QGxAeoBY2YSsAGMAZIBDPQBGWwExgJBkgKNATxNHGUC"
  + "b2O/ASN1OU2RAV1jJ1UQBRcuMQA5VytXE5MBFs0BT5IBKR4tJ0tbI6UCJVUlaBJIES5BKBPMARvwAhCcAQ0RtwEhG8MCbUNN"
  + "Ey+9AQhZMZkBIekBT18NmwMy9wEF0QItVwaFAkibAQ6DASZSTbcBSd8CIacBCkZjSxm7AiItCSkfcxDlAVp9EGUHlQNVU1Up"
  + "eTtrYVNzC2s4zQE+Wy5nI9MBE98BNZsCgwEnG0dhbRFhPHEWdxVHIyMcADZWQOQBMsgBgAGKAXowHD4KIDCYAsIBOsoB5AEy"
  + "bKAB2gIq6gED6AEh8AEKXiqgAZ4BpALKAZwBhAG1Ap8B7QEtvQKVAY0CGMkBfoEBNDcGrQEhdwQ8OlIguQEWbzzXAQV3N7kB"
  + "O98BUC0iAEQhNj8STkZgLtIBLu4DnAHqAYABZJYBRkJFEB8yCDIeLk90EGD/ARPlAVVlCQImLDDoAXpOXDwmnAFK3AJadgvA"
  + "AjLkAVlFhgFmIJIBeTYPchKlASg5KF96BEqGAZIBayoPRhQ+fjYmVESlMfylAycZAy8aPTQrTMkBND8MvQEXGWqTAhKlAWd5"
  + "KUcfSxN5gQGPAXc5jAFlcy19D4kBGlUFbTMZCDVSJ1VPG4cBBOEBF1kZYWn5ATtRR2spEPJsgr4CLQsbDA8QEiZaFwMXFw0K"
  + "vjGGogONASMjCIIBHiwFCqou0qEDxwERTxjeAQo2Ewr0J7ygA7kBSxEMeEBQAwzOKYqhA18JKw7iASimAQaBAjUM0RPWggMl"
  + "Q10WBxJoJh4NEOMP0IADCDUtCycSkQENEFqKAQtAGRjlIMqgAyoVaAQjK6MCgwEtLDcDU1QPfmoikgEDeGEYqwiCjANVIy85"
  + "OQ03ANMBUjEFMCaCAR5KKKgBKU4tDJYmzp4DY0dPJB44kgFcAHMWnFHqzgIkPxcbCjlVMIEBG00GFywSGOYBDCYkDJ5CnLEC"
  + "OWU/RgM8CBJwMQ7eQNDAAiMvLwQ+ZjQWGBU7PxbGIaK3AhMNtQJ0ZQwbEgxYzgEMpgEtWnMGFR05DpQKxrACAjIuMNgBKjIj"
  + "CjODAWsU7h6clANgOR4lfxWDAUJZESEgAxRcEKABBwzONM6iA10DGhpWFC4AQy1Y2m2A3wJNXWsCd5oBcXQbfFf6AXg2kgFc"
  + "nQGOAUcAXT2FAj4zGyUxWz1/HY8BQ4kCU0MGaEwtAtsBZTHNATwjaqkBhAFJPXtRMUEkKwMfbzilAlzPAVpbzgGNAdgBSYQD"
  + "7QHUAUs4KYIBtwFu0wF4yQJWowFa4G2mvwK9AYQCf2pBEnUXwQEudQqfAS0vFhMirwFs3QE+qQPWAoMBgAGNAo4BqwHOAY0B"
  + "SssBPpsBIycaUCgRUOcBygGHAUJhhAFBFoMBChKsAQ1ASagBgQGOAUvSAjtgjQFIvwJSuQPaAV8CiwJWpQEO1wFNhQLTAdMB"
  + "2wFPK48CS/EBI0K6GbrRAs8BlwIJTy75AWyBASpfMBkSOY0BIRFfSjMOHwqLAfUBsQG3Ba8CpQGTAUEhhQRdlwSHAb8C8QFS"
  + "E2BTISWNATl9EekBpwLPAdcBc115iwH9AeUCAGd85QJGXUTFPq7VApgBDJoBOmglWgxoLYoBZ8oBKaABIJoCBo4BD/wBGpAB"
  + "C+oBNLQBQd4CHdIBNcYEV9QBA6gCMn4kdBeqASpQCWo99AJRYkRIDowCK44CVY4BB8wBGKQBNsQBJpwB3BOajwO0A6gBigJW"
  + "yAEqpAEGfh+oARGAASpkJXIa3QE6uQEjgQEobQSLAVY0JDAOxAEGjgEXgAJ3hAEQIyChATBNLLIBDjE+vQGKAVB2OkJ8QKgB"
  + "igFqclCEAXTwAlqEAXgjrgE0qAKIAVh2VjbWAmy8ASDyBSKYAXPmAS8vLGMyNrQBYmJQHNgCEPwCCZ4BkwE9TVwlLg44igEg"
  + "FnY3KCcEeSqiASFyFnBaXpgCKbQCFHQriALXAVgjbg2ZAS7BAoQCYSCTAQhdGjsoESIM5lT6pQNAD7oBDqgCQz4U7gGWAQb+"
  + "a4SmAyynAaABVwrgbeikA3sQGToUOjMo";

/* Les frontières des pays voisins, 26 morceaux, 445 points. */
const BORNES =
  "NFT2a/78Ai0y3wGQAW0FJxY/UjUmlQE84QGsAWcAhQFUtwHiAW9kbHIOKjc8twFWRTgjTlVcACIsCCgXOi0uP64BqAFiLJwB"
  + "EDwUsAEZGAoySqYBFDhCRApEJD4VJA42TB4MkgEMigNqFMgxrIIDIpQBHCxOQARapQEoeU5DOh08BlYU5C/IhwMbInMOb1dP"
  + "eS0rFXFAM1xzQVsG9mv+/AKuAUs+W2yQN9DmAkoZxgEg0gFC+gE5zgFehAGQAQIcL0QOEIgBRooBaDQAFC0FeRQluAGJAbAB"
  + "IQgRMUNsTxI5MiFGEBYeMWwGHhImtgGoATBCCL4BLBR8DzaHAS4rcAv0AUg4B2Z9JgswChIQJWwdOiUcCSQydGwWTDueAQ8I"
  + "RCkwCEQuggEW1FGQ7gICJClAQRSrAXsvC4sBInc0IUZlHqcBFFieOKKgAwmbAklxRZEBE10TE4sCACcRCC0bLQofLiVUF4gB"
  + "AkRBEXMrPf8BfwktVjkDDTs74QE5XwRFI78BONsBTwApjgF9AilmbwQnIWFbgwEGLTYRBxG/AW1JBgsRJC9wIyovN5sBCOxK"
  + "0u8CHjI3Th1UEIZupuMCXyAXBwAXIyE7F4cCMCcoEuouvowD8gGbAUUzJC9aDy4jGIkBvQFVPXEm1FGQ7gLuARNGNUQTpgEA"
  + "IBRsjAFuKJwCFvgBDYoDYCAXSU0YMeoB6wFcH7AFZcICEdIBJSqEa7jrAhU7dS+lAWMXOSwzRgSMAScRLYMBXwcfHiVaBg4T"
  + "LYEBDheKATNuUypDHxd9BQSBDuzSAgMkBNAYwMsCPAAMlAvkzAIPMQ5XFBlWBKwBPhaCIbqRAzdPhQE9iwEpSQSVAUBnCm0t"
  + "KQQ1Lh9WOuouvowD9wEKNw43RggWZlQAJkRiCighHL0BLIUBWKcBG2ESc0QpbB8QVz9hBR0ICyg3KHtHLwBVNHkvFD0fDZUB"
  + "Hiq0SqTzAtcCkgGtAg8zMCcMQxFvQi8KPwtLIyEtChsmC3QACR1rHYECCmkfpwEN5wEGUxYIuEqm8QJSehBMZzgI7ErS7wJd"
  + "BAVuLGIM5jTQ6gK1ARaXAQlrJVk/BRlu3zbKsAIIRi00gwEchwHKAR+AAW9GW35SEtACAlIgPFRAjAEQVBUicVYFGhIozAGI"
  + "AStkItIBE3wXZEeEAS40ai5WanxaogFIclAuPCAQCxwXKkEoVRiXAQYRIACqARMoKxxXCYMBHiETpQEEdyAxGw89OyGJAR9t"
  + "ArcBNMsBExkOrwFHdPZr/vwCHbMBPy8xE78BOhsTM6sBJSE1H/EBObkBSVUtNzcAH8IBuwEAUzlXiAEZFCsHTSNnLwOfAUId"
  + "Fg4sGSBXHs0BIXcymwEeDwkIQRMb1wMlxQJhEx1NJVcLFQyXASE/BFdIFTKFAQRVGNsBBCWJASMzOzWBASUQVocBHggiDxZZ"
  + "OOEBRmMzfwMExG2S6wLBAiYOmmHO1wIvMR4pPAgcMgsmPwkGjmGyxwIKCQsI";

/* Décodage. Chaque ligne devient un tableau plat de longitudes et de latitudes
   alternées, en degrés : c'est la forme que le tracé consomme, sans objet
   intermédiaire par point. */
function lecteur(b64) {
  const bin = atob(b64);
  let i = 0;
  return () => {
    let v = 0, d = 0, b;
    do { b = bin.charCodeAt(i++); v |= (b & 0x7f) << d; d += 7; } while (b & 0x80);
    return (v & 1) ? -(v >>> 1) : (v >>> 1);
  };
}

function decoder(b64) {
  const suivant = lecteur(b64);
  const lignes = [];
  const n = suivant();
  for (let k = 0; k < n; k++) {
    const m = suivant();
    const l = new Float64Array(m * 2);
    let x = 0, y = 0;
    for (let j = 0; j < m; j++) {
      x += suivant(); y += suivant();
      l[j * 2] = x * PAS; l[j * 2 + 1] = y * PAS;
    }
    lignes.push(l);
  }
  return lignes;
}

/* Les couches, décodées une seule fois. Le décodage de 8047 points prend
   quelques millisecondes, et la carte se redessine à chaque geste : le refaire à
   chaque image serait le seul calcul lourd du tracé. */
let jeu = null;
function charger() {
  if (jeu) return jeu;
  const arcs = decoder(ARCS);
  const suivant = lecteur(INDEX);
  const codes = CODES.split(",");
  const deps = new Map();
  const usage = new Int8Array(arcs.length);
  const n = suivant();
  for (let k = 0; k < n; k++) {
    const anneaux = [];
    const na = suivant();
    for (let a = 0; a < na; a++) {
      const nr = suivant();
      const suite = new Int32Array(nr);
      for (let r = 0; r < nr; r++) {
        const v = suivant();
        suite[r] = v;
        const rang = v < 0 ? ~v : v;
        if (usage[rang] < 2) usage[rang]++;
      }
      anneaux.push(suite);
    }
    deps.set(codes[k], anneaux);
  }
  jeu = { arcs, deps, usage,
    terre: decoder(TERRE), bornes: decoder(BORNES) };
  return jeu;
}

/* Les quatre couches du tracé. Le contour porte les arcs qu'un seul département
   touche, les limites intérieures ceux que deux départements partagent. */
let couches = null;
export function contours() {
  if (!couches) {
    const j = charger();
    couches = {
      contour: j.arcs.filter((_, i) => j.usage[i] === 1),
      departements: j.arcs.filter((_, i) => j.usage[i] > 1),
      terre: j.terre,
      bornes: j.bornes,
    };
  }
  return couches;
}

/* Les anneaux d'un département, en tableaux plats de longitudes et de latitudes.
   Le premier point de chaque arc répète le dernier du précédent : il se saute,
   sans quoi le tracé reviendrait sur lui-même à chaque jonction. */
const anneauxCache = new Map();
export function anneauxDe(code) {
  if (anneauxCache.has(code)) return anneauxCache.get(code);
  const j = charger();
  const suites = j.deps.get(code);
  if (!suites) { anneauxCache.set(code, null); return null; }
  const out = suites.map(suite => {
    const pts = [];
    for (const v of suite) {
      const a = j.arcs[v < 0 ? ~v : v];
      const m = a.length / 2;
      if (v < 0) {
        for (let k = m - 1; k >= 0; k--) {
          if (k === m - 1 && pts.length) continue;
          pts.push(a[k * 2], a[k * 2 + 1]);
        }
      } else {
        for (let k = 0; k < m; k++) {
          if (k === 0 && pts.length) continue;
          pts.push(a[k * 2], a[k * 2 + 1]);
        }
      }
    }
    return Float64Array.from(pts);
  });
  anneauxCache.set(code, out);
  return out;
}

// Les codes des départements portés par le fichier.
export const codesDepartements = () => [...charger().deps.keys()];
